//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babe.Lua.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.LuaTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CompletionExample {
            get {
                object obj = ResourceManager.GetObject("CompletionExample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CompletionLua51 {
            get {
                object obj = ResourceManager.GetObject("CompletionLua51", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be delete. Please confirm..
        /// </summary>
        public static string DeleteFileConfirm {
            get {
                return ResourceManager.GetString("DeleteFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure Delete？.
        /// </summary>
        public static string DeleteSetConfirm {
            get {
                return ResourceManager.GetString("DeleteSetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Explorer.
        /// </summary>
        public static string FolderWindowTitle {
            get {
                return ResourceManager.GetString("FolderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to set lua executable path first..
        /// </summary>
        public static string GuideLuaExecutablePath {
            get {
                return ResourceManager.GetString("GuideLuaExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find lua executable in target path..
        /// </summary>
        public static string InvalidLuaExecutablePath {
            get {
                return ResourceManager.GetString("InvalidLuaExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid lua folder..
        /// </summary>
        public static string InvalidLuaPath {
            get {
                return ResourceManager.GetString("InvalidLuaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--You must restart visual studio for the changes to take effect--&gt;
        ///&lt;Keywords&gt;
        ///  &lt;C r=&quot;163&quot; g=&quot;73&quot; b=&quot;164&quot;&gt;
        ///    &lt;word&gt;res_create_image&lt;/word&gt;
        ///    &lt;word&gt;res_create_text_image&lt;/word&gt;
        ///    &lt;word&gt;res_print&lt;/word&gt;
        ///    &lt;word&gt;res_alloc_id&lt;/word&gt;
        ///    &lt;word&gt;res_free_id&lt;/word&gt;
        ///    &lt;word&gt;res_get_array_size&lt;/word&gt;
        ///    &lt;word&gt;res_get_image_width&lt;/word&gt;
        ///    &lt;word&gt;res_get_image_height&lt;/word&gt;
        ///    &lt;word&gt;res_delete&lt;/word&gt;
        ///    &lt;word&gt;res_delete_group&lt;/word&gt;
        ///    &lt;word&gt;anim_cr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KeyWords {
            get {
                return ResourceManager.GetString("KeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a lua folder setting first.
        /// </summary>
        public static string LoseCurrentSetting {
            get {
                return ResourceManager.GetString("LoseCurrentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Lua Folder.
        /// </summary>
        public static string LoseLuaPath {
            get {
                return ResourceManager.GetString("LoseLuaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Name.
        /// </summary>
        public static string LoseSetName {
            get {
                return ResourceManager.GetString("LoseSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Failed. Result：{0}.
        /// </summary>
        public static string LuaExecutableError {
            get {
                return ResourceManager.GetString("LuaExecutableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Explorer.
        /// </summary>
        public static string OutlineWindowTitle {
            get {
                return ResourceManager.GetString("OutlineWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Setting with this name already exists.
        /// </summary>
        public static string RepeatSetName {
            get {
                return ResourceManager.GetString("RepeatSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result 1.
        /// </summary>
        public static string SearchlWindowTitle1 {
            get {
                return ResourceManager.GetString("SearchlWindowTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result 2.
        /// </summary>
        public static string SearchlWindowTitle2 {
            get {
                return ResourceManager.GetString("SearchlWindowTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Settings&gt;
        ///	&lt;LuaSettings&gt;
        ///		&lt;CurrentSet&gt;&lt;/CurrentSet&gt;
        ///	&lt;/LuaSettings&gt;
        ///	&lt;SearchFilters&gt;
        ///		&lt;local /&gt;
        ///		&lt;do /&gt;
        ///		&lt;while /&gt;
        ///		&lt;for /&gt;
        ///		&lt;end /&gt;
        ///		&lt;function /&gt;
        ///		&lt;if /&gt;
        ///		&lt;then /&gt;
        ///		&lt;elseif /&gt;
        ///		&lt;and /&gt;
        ///		&lt;or /&gt;
        ///		&lt;not /&gt;
        ///		&lt;true /&gt;
        ///		&lt;false /&gt;
        ///		&lt;nil /&gt;
        ///		&lt;return /&gt;
        ///		&lt;repeat /&gt;
        ///		&lt;until /&gt;
        ///		&lt;in /&gt;
        ///		&lt;break /&gt;
        ///	&lt;/SearchFilters&gt;
        ///	&lt;UISettings&gt;
        ///		&lt;HideUselessView&gt;0&lt;/HideUselessView&gt;
        ///	&lt;/UISettings&gt;
        ///	&lt;KeyBinding&gt;&lt;/KeyBinding&gt;
        ///	&lt;Highlight&gt;
        ///		&lt;Tab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingWindotTitle {
            get {
                return ResourceManager.GetString("SettingWindotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--You must restart visual studio for the changes to take effect--&gt;
        ///&lt;Keywords&gt;
        ///	&lt;!--support at most 15 groups--&gt;
        ///	&lt;User r=&quot;0&quot; g=&quot;0&quot; b=&quot;255&quot;&gt;
        ///		&lt;word&gt;add_your_keyword_like_this&lt;/word&gt;
        ///	&lt;/User&gt;
        ///	&lt;User r=&quot;255&quot; g=&quot;0&quot; b=&quot;0&quot;&gt;
        ///		&lt;word&gt;add_your_keyword_like_this&lt;/word&gt;
        ///	&lt;/User&gt;
        ///&lt;/Keywords&gt;.
        /// </summary>
        public static string UserKeyWords {
            get {
                return ResourceManager.GetString("UserKeyWords", resourceCulture);
            }
        }
    }
}
